#---------------------------General Params-------------------------------------#


case : "ML_avrm_rk4"

data_folder : 'data_ML_4_'
plots_folder : 'plots_ML_4_'


#--------------------------Time Params--------------------------------------#
nTimeSteps : 1000    #number of lagrangian time-steps
writeInterval_plots : 100
compression_stride : 500  # number of timesteps between compressions

deltaTc : 0.02      #lagrangian, convection time-step

#---------------------------Lagrangian Params-------------------------------------#

xMin : [-0.5]         #minimum x for initial blobs
xMax : [0.5]          #maximum x for initial blobs
yMin : [-0.5]         #minimum y for initial blobs
yMax : [0.5]          #maximum y for initial blobs

vInfx : 0.0           #freestream velocity in x direction
vInfy : 0.0           #freestream velocity in y direction
sigma : 0.010              #blob core radius
overlap : 1.0         #blobs' overlap ratio

nTimeSteps : 1000    #number of lagrangian time-steps
nu : 0.001
gammaC : 1.0

  #Computation Params
hardware : "gpu"
method : "direct"

  #Blob Control Params
method_popControl : 'implicit'
stepRedistribution : 0
stepPopulationControl : 1
gThresholdLocal : 1e-12
gThresholdGlobal : 1e-12
blobsRedistribute : 'all'

  #Blob Diffusion Params
method_diffusion : 'adaptive_vrm'

  #Time integration Params
time_integration_method : 'rk4'

  #Kernel params
kernel : 'gauss'
coreSize : 'variable'

  #xShift,yShift
xShift : 0.0
yShift : 0.0

#--------------------------- Compression Params -------------------------------------#

compressionFlag : True

compression_method : 'multiscale'
compression_params : {'Csigma' : 1., 'margin' : 0.05, 'sigma_max' : 0.1, 'sigma_min' : 0.01, 'radius_check' : 1.2, 'compression' : 0.10, 'type' : 'induced', 'ignore' : True}

# support_method : 'radial'
# support_params : {'x0' : 0., 'y0' : 0.}

# compression_func_values: {'x0' : 0.01, 'y0' : 0.95, 'x1' : 2., 'y1' : 0.01}
# support_func_values : {'step' : 0.5, 'start' : 0.0, 'end' : 2.5}
support_method : 'all'
support_params : {}

#---------------------------Plot Params-------------------------------------#
nPlotPoints : 100    #plot points in each direction
xMinPlot : -2.0       #minimum x to plot
xMaxPlot : 2.0       #maximum x to plot
yMinPlot : -2.0       #minimum y to plot
yMaxPlot : 2.0        #maximum y to plot


run_analytical_flag : True
plot_flag : True